In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
frd = pd.read_csv(r"C:\Users\Muralidhar\Fraud_check.csv")
frd

Undergrad Marital.Status  Taxable.Income  City.Population  \
0          NO         Single           68833            50047   
1         YES       Divorced           33700           134075   
2          NO        Married           36925           160205   
3         YES         Single           50190           193264   
4          NO        Married           81002            27533   
..        ...            ...             ...              ...   
595       YES       Divorced           76340            39492   
596       YES       Divorced           69967            55369   
597        NO       Divorced           47334           154058   
598       YES        Married           98592           180083   
599        NO       Divorced           96519           158137   

     Work.Experience Urban  
0                 10   YES  
1                 18   YES  
2                 30   YES  
3                 15   YES  
4                 28    NO  
..               ...   ...  
595                7   YES  
596                2   YES  
597                0   YES  
598               17    NO  
599               16    NO  

[600 rows x 6 columns]

In [3]:
frd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   Undergrad        600 non-null    object
 1   Marital.Status   600 non-null    object
 2   Taxable.Income   600 non-null    int64 
 3   City.Population  600 non-null    int64 
 4   Work.Experience  600 non-null    int64 
 5   Urban            600 non-null    object
dtypes: int64(3), object(3)
memory usage: 28.2+ KB


In [4]:
frd.describe()

Taxable.Income  City.Population  Work.Experience
count      600.000000       600.000000       600.000000
mean     55208.375000    108747.368333        15.558333
std      26204.827597     49850.075134         8.842147
min      10003.000000     25779.000000         0.000000
25%      32871.500000     66966.750000         8.000000
50%      55074.500000    106493.500000        15.000000
75%      78611.750000    150114.250000        24.000000
max      99619.000000    199778.000000        30.000000

In [5]:
frd.dtypes

Undergrad          object
Marital.Status     object
Taxable.Income      int64
City.Population     int64
Work.Experience     int64
Urban              object
dtype: object

In [6]:
frd.shape

(600, 6)

In [7]:
frd.isnull().sum()

Undergrad          0
Marital.Status     0
Taxable.Income     0
City.Population    0
Work.Experience    0
Urban              0
dtype: int64

In [10]:
frd.loc[frd['Taxable.Income'] <=30000,'Taxable_Income']= 'Risky'
frd.loc[frd['Taxable.Income'] >30000,'Taxable_Income']= 'Good'

In [11]:
frd

Undergrad Marital.Status  Taxable.Income  City.Population  \
0          NO         Single           68833            50047   
1         YES       Divorced           33700           134075   
2          NO        Married           36925           160205   
3         YES         Single           50190           193264   
4          NO        Married           81002            27533   
..        ...            ...             ...              ...   
595       YES       Divorced           76340            39492   
596       YES       Divorced           69967            55369   
597        NO       Divorced           47334           154058   
598       YES        Married           98592           180083   
599        NO       Divorced           96519           158137   

     Work.Experience Urban Taxable_Income  
0                 10   YES           Good  
1                 18   YES           Good  
2                 30   YES           Good  
3                 15   YES           Good  
4                 28    NO           Good  
..               ...   ...            ...  
595                7   YES           Good  
596                2   YES           Good  
597                0   YES           Good  
598               17    NO           Good  
599               16    NO           Good  

[600 rows x 7 columns]

In [12]:
frd.drop('Taxable.Income',1,inplace=True)

C:\Users\MURALI~1\AppData\Local\Temp/ipykernel_5260/1286609968.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  frd.drop('Taxable.Income',1,inplace=True)


In [13]:
frd['Marital.Status'].value_counts()

Single      217
Married     194
Divorced    189
Name: Marital.Status, dtype: int64

In [14]:
from sklearn import preprocessing 
label_encoder = preprocessing.LabelEncoder() 
frd['Marital.Status']= label_encoder.fit_transform(frd['Marital.Status']) 
frd['Marital.Status'].unique() 

array([2, 0, 1])

In [15]:
frd

Undergrad  Marital.Status  City.Population  Work.Experience Urban  \
0          NO               2            50047               10   YES   
1         YES               0           134075               18   YES   
2          NO               1           160205               30   YES   
3         YES               2           193264               15   YES   
4          NO               1            27533               28    NO   
..        ...             ...              ...              ...   ...   
595       YES               0            39492                7   YES   
596       YES               0            55369                2   YES   
597        NO               0           154058                0   YES   
598       YES               1           180083               17    NO   
599        NO               0           158137               16    NO   

    Taxable_Income  
0             Good  
1             Good  
2             Good  
3             Good  
4             Good  
..             ...  
595           Good  
596           Good  
597           Good  
598           Good  
599           Good  

[600 rows x 6 columns]

In [16]:
frd.Undergrad.value_counts()

YES    312
NO     288
Name: Undergrad, dtype: int64

In [18]:
frd['Undergrad']= label_encoder.fit_transform(frd['Undergrad']) 
frd['Undergrad'].unique() 

array([0, 1])

In [19]:
frd.Urban.value_counts()

YES    302
NO     298
Name: Urban, dtype: int64

In [20]:
frd['Urban']= label_encoder.fit_transform(frd['Urban']) 
frd['Urban'].unique() 

array([1, 0])

In [21]:
frd

Undergrad  Marital.Status  City.Population  Work.Experience  Urban  \
0            0               2            50047               10      1   
1            1               0           134075               18      1   
2            0               1           160205               30      1   
3            1               2           193264               15      1   
4            0               1            27533               28      0   
..         ...             ...              ...              ...    ...   
595          1               0            39492                7      1   
596          1               0            55369                2      1   
597          0               0           154058                0      1   
598          1               1           180083               17      0   
599          0               0           158137               16      0   

    Taxable_Income  
0             Good  
1             Good  
2             Good  
3             Good  
4             Good  
..             ...  
595           Good  
596           Good  
597           Good  
598           Good  
599           Good  

[600 rows x 6 columns]

In [23]:
colnames = list(frd.columns)
predictors = colnames[0:5]
target = colnames[5]

In [24]:
predictors

['Undergrad', 'Marital.Status', 'City.Population', 'Work.Experience', 'Urban']

In [25]:
target

'Taxable_Income'

In [26]:
X = frd[predictors]
Y = frd[target]

In [27]:
X

Undergrad  Marital.Status  City.Population  Work.Experience  Urban
0            0               2            50047               10      1
1            1               0           134075               18      1
2            0               1           160205               30      1
3            1               2           193264               15      1
4            0               1            27533               28      0
..         ...             ...              ...              ...    ...
595          1               0            39492                7      1
596          1               0            55369                2      1
597          0               0           154058                0      1
598          1               1           180083               17      0
599          0               0           158137               16      0

[600 rows x 5 columns]

In [28]:
Y

0      Good
1      Good
2      Good
3      Good
4      Good
       ... 
595    Good
596    Good
597    Good
598    Good
599    Good
Name: Taxable_Income, Length: 600, dtype: object

In [29]:
 from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_jobs=2,oob_score=True,n_estimators=1000,criterion="entropy")
rf.fit(X,Y)

RandomForestClassifier(criterion='entropy', n_estimators=1000, n_jobs=2,
                       oob_score=True)

In [30]:
frd['rf_pred'] = rf.predict(X)

In [32]:
from sklearn.metrics import confusion_matrix
confusion_matrix(frd['Taxable_Income'],frd['rf_pred'])

array([[476,   0],
       [  0, 124]], dtype=int64)

In [33]:
frd

Undergrad  Marital.Status  City.Population  Work.Experience  Urban  \
0            0               2            50047               10      1   
1            1               0           134075               18      1   
2            0               1           160205               30      1   
3            1               2           193264               15      1   
4            0               1            27533               28      0   
..         ...             ...              ...              ...    ...   
595          1               0            39492                7      1   
596          1               0            55369                2      1   
597          0               0           154058                0      1   
598          1               1           180083               17      0   
599          0               0           158137               16      0   

    Taxable_Income rf_pred  
0             Good    Good  
1             Good    Good  
2             Good    Good  
3             Good    Good  
4             Good    Good  
..             ...     ...  
595           Good    Good  
596           Good    Good  
597           Good    Good  
598           Good    Good  
599           Good    Good  

[600 rows x 7 columns]

In [35]:
frd.value_counts()

Undergrad  Marital.Status  City.Population  Work.Experience  Urban  Taxable_Income  rf_pred
0          0               27300            1                1      Good            Good       1
1          1               55591            0                1      Good            Good       1
                           57194            25               0      Good            Good       1
                           59590            29               0      Good            Good       1
                           60999            15               1      Risky           Risky      1
                                                                                              ..
0          2               48025            28               1      Good            Good       1
                           49505            25               0      Good            Good       1
                           50047            10               1      Good            Good       1
                           50495   

In [37]:
frd.loc[frd['Taxable_Income'].isin(["Risky"])]

Undergrad  Marital.Status  City.Population  Work.Experience  Urban  \
10           0               2           102602               19      1   
12           0               0           148033               14      1   
16           1               0            34551               29      0   
19           0               2           126953               30      1   
21           1               0            29106                7      1   
..         ...             ...              ...              ...    ...   
544          0               2           133877               21      1   
557          1               1           157421               10      0   
567          1               2           129912               30      0   
575          0               0            95975               13      1   
591          1               2           132859               18      1   

    Taxable_Income rf_pred  
10           Risky   Risky  
12           Risky   Risky  
16           Risky   Risky  
19           Risky   Risky  
21           Risky   Risky  
..             ...     ...  
544          Risky   Risky  
557          Risky   Risky  
567          Risky   Risky  
575          Risky   Risky  
591          Risky   Risky  

[124 rows x 7 columns]

In [41]:
frd.loc[frd['Taxable_Income'].isin(["Risky"])].value_counts()

Undergrad  Marital.Status  City.Population  Work.Experience  Urban  Taxable_Income  rf_pred
0          0               33184            1                0      Risky           Risky      1
1          1               39797            11               0      Risky           Risky      1
                           138108           28               0      Risky           Risky      1
                           137676           3                1      Risky           Risky      1
                           128266           24               1      Risky           Risky      1
                                                                                              ..
0          2               32450            19               1      Risky           Risky      1
           1               197841           7                0      Risky           Risky      1
                           173091           14               0      Risky           Risky      1
                           131906  

In [42]:
#from the analysis in random forest it is found that how many are in risky category and how many are good